export const airportsByCountry: Record<string, string[]> = {
  'Pakistan': [
    'Islamabad International Airport (ISB)',
    'Jinnah International Airport, Karachi (KHI)',
    'Allama Iqbal International Airport, Lahore (LHE)',
    'Peshawar Bacha Khan International Airport (PEW)',
    'Quetta International Airport (UET)',
    'Faisalabad International Airport (LYP)',
    'Multan International Airport (MUX)',
    'Sialkot International Airport (SKT)',
  ],
  'United Kingdom': [
    'London Heathrow Airport (LHR)',
    'London Gatwick Airport (LGW)',
    'London Stansted Airport (STN)',
    'London Luton Airport (LTN)',
    'Manchester Airport (MAN)',
    'Birmingham Airport (BHX)',
    'Edinburgh Airport (EDI)',
    'Glasgow Airport (GLA)',
    'Bristol Airport (BRS)',
    'Leeds Bradford Airport (LBA)',
    'Liverpool John Lennon Airport (LPL)',
    'London City Airport (LCY)',
  ],
  'United States': [
    'John F. Kennedy International Airport, New York (JFK)',
    'Los Angeles International Airport (LAX)',
    'Chicago O\'Hare International Airport (ORD)',
    'Hartsfield-Jackson Atlanta International Airport (ATL)',
    'Dallas/Fort Worth International Airport (DFW)',
    'Denver International Airport (DEN)',
    'San Francisco International Airport (SFO)',
    'Seattle-Tacoma International Airport (SEA)',
    'Orlando International Airport (MCO)',
    'Miami International Airport (MIA)',
    'Newark Liberty International Airport (EWR)',
    'Washington Dulles International Airport (IAD)',
    'Boston Logan International Airport (BOS)',
    'Houston George Bush Intercontinental Airport (IAH)',
  ],
  'Canada': [
    'Toronto Pearson International Airport (YYZ)',
    'Vancouver International Airport (YVR)',
    'Montréal-Pierre Elliott Trudeau International Airport (YUL)',
    'Calgary International Airport (YYC)',
    'Edmonton International Airport (YEG)',
    'Ottawa Macdonald-Cartier International Airport (YOW)',
    'Winnipeg James Armstrong Richardson International Airport (YWG)',
    'Halifax Stanfield International Airport (YHZ)',
  ],
  'Nigeria': [
    'Murtala Muhammed International Airport, Lagos (LOS)',
    'Nnamdi Azikiwe International Airport, Abuja (ABV)',
    'Mallam Aminu Kano International Airport (KAN)',
    'Port Harcourt International Airport (PHC)',
    'Akanu Ibiam International Airport, Enugu (ENU)',
  ],
  'India': [
    'Indira Gandhi International Airport, New Delhi (DEL)',
    'Chhatrapati Shivaji Maharaj International Airport, Mumbai (BOM)',
    'Kempegowda International Airport, Bengaluru (BLR)',
    'Rajiv Gandhi International Airport, Hyderabad (HYD)',
    'Chennai International Airport (MAA)',
    'Netaji Subhas Chandra Bose International Airport, Kolkata (CCU)',
    'Cochin International Airport (COK)',
    'Goa Manohar International Airport (GOX)',
    'Sardar Vallabhbhai Patel International Airport, Ahmedabad (AMD)',
    'Jaipur International Airport (JAI)',
  ],
  'Germany': [
    'Frankfurt Airport (FRA)',
    'Munich Airport (MUC)',
    'Berlin Brandenburg Airport (BER)',
    'Düsseldorf Airport (DUS)',
    'Hamburg Airport (HAM)',
    'Cologne Bonn Airport (CGN)',
    'Stuttgart Airport (STR)',
    'Hanover Airport (HAJ)',
  ],
  'France': [
    'Paris Charles de Gaulle Airport (CDG)',
    'Paris Orly Airport (ORY)',
    'Nice Côte d\'Azur Airport (NCE)',
    'Lyon-Saint Exupéry Airport (LYS)',
    'Marseille Provence Airport (MRS)',
    'Toulouse-Blagnac Airport (TLS)',
    'Bordeaux-Mérignac Airport (BOD)',
    'Nantes Atlantique Airport (NTE)',
  ],
  'Australia': [
    'Sydney Kingsford Smith Airport (SYD)',
    'Melbourne Airport (MEL)',
    'Brisbane Airport (BNE)',
    'Perth Airport (PER)',
    'Adelaide Airport (ADL)',
    'Gold Coast Airport (OOL)',
    'Cairns Airport (CNS)',
    'Canberra Airport (CBR)',
  ],
  'Philippines': [
    'Ninoy Aquino International Airport, Manila (MNL)',
    'Mactan-Cebu International Airport (CEB)',
    'Clark International Airport (CRK)',
    'Francisco Bangoy International Airport, Davao (DVO)',
    'Iloilo International Airport (ILO)',
    'Kalibo International Airport (KLO)',
    'Puerto Princesa International Airport (PPS)',
    'Laguindingan Airport, Cagayan de Oro (CGY)',
  ],
  'Japan': [
    'Tokyo Narita International Airport (NRT)',
    'Tokyo Haneda Airport (HND)',
    'Kansai International Airport, Osaka (KIX)',
    'Chubu Centrair International Airport, Nagoya (NGO)',
    'New Chitose Airport, Sapporo (CTS)',
    'Fukuoka Airport (FUK)',
    'Naha Airport, Okinawa (OKA)',
  ],
  'South Korea': [
    'Incheon International Airport, Seoul (ICN)',
    'Gimpo International Airport, Seoul (GMP)',
    'Gimhae International Airport, Busan (PUS)',
    'Jeju International Airport (CJU)',
    'Daegu International Airport (TAE)',
  ],
  'Singapore': [
    'Singapore Changi Airport (SIN)',
  ],
  'Ireland': [
    'Dublin Airport (DUB)',
    'Cork Airport (ORK)',
    'Shannon Airport (SNN)',
    'Ireland West Airport Knock (NOC)',
  ],
};
